name: maxsociety
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  dio: ^5.0.1
  file_picker: ^5.2.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.15
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.0+1
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.3
  group_radio_button: ^1.3.0
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  introduction_screen: ^3.1.4
  photo_view: ^0.14.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  string_validator: ^0.3.0
  tab_indicator_styler: ^2.0.0
  timeago: ^3.3.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/svg/
    - assets/banner/
    - assets/image/

flutter_native_splash:
  image: assets/logo/splash.png
  color: "#ffffff"
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo_512.png"
  # adaptive_icon_background: "#ffffff"
# flutter pub run flutter_launcher_icons:main
