// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDukQp0AJffCGnUe8xetz9PCRXQOC0jW8Q',
    appId: '1:819843411741:web:150a6827c6a9b72e20bbf4',
    messagingSenderId: '819843411741',
    projectId: 'max-society',
    authDomain: 'max-society.firebaseapp.com',
    storageBucket: 'max-society.appspot.com',
    measurementId: 'G-3W87F321V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3JBhIxp8bQxcvR4rdvCWpLa2YeIvFUuk',
    appId: '1:819843411741:android:ee365ecfc300ae3920bbf4',
    messagingSenderId: '819843411741',
    projectId: 'max-society',
    storageBucket: 'max-society.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4NVuB3I6TIztkBmvJCph7cja_j908Po',
    appId: '1:819843411741:ios:0d7fde29919e2a6d20bbf4',
    messagingSenderId: '819843411741',
    projectId: 'max-society',
    storageBucket: 'max-society.appspot.com',
    iosClientId: '819843411741-2j6o5hc9am3dg0ao3hq14cf8tl6its61.apps.googleusercontent.com',
    iosBundleId: 'com.maxsociety.maxsociety',
  );
}
